### PR TITLE
Added alternative behavior if multiprocessing module is missing

### PR DESCRIPTION
**Pull request by madeddy**
Like talked about in #106

### CODE REVIEW

**Comment by CensoredUsername** [comment]
There's a lot of changes in that file seemingly not related to your code but just changing random formatting, could you restrict the pull to just the actual changes necessary?

**Comment by madeddy** [comment]
A lot? The empty lines where just from some autoformat feat for py styleguide/pep8. I tested VScode again for usability as i did the changes. Normally i am in Atom.
Removed all the spaces, though i think it's formatting is not useless. Please check and write what you think.

**Comment by jackmcbarn** [comment]
> A lot? The empty lines where just from some autoformat feat for py styleguide/pep8. I tested VScode again for usability as i did the changes. Normally i am in Atom.
> Removed all the spaces, though i think it's formatting is not useless. Please check and write what you think.

The problem with those blank lines isn't that they're useless; it's that they're unrelated to the purpose of this PR. If you want, you could make a separate PR that makes all of unrpyc be PEP8-compliant.

**Comment by madeddy** [comment]
Ah,ok. This can i completely understand and see the use of it. Thanks for explaining. In this case i should also fit the formatting of the one argparse option to the others.

**Comment by CensoredUsername** [comment]
I squashed and rebased stuff onto dev to get rid of the 4 bugfix commits, and did some cleanup. It's now mainlined!

**Pull request closed without merging**
