### PR TITLE
Dev: translation refactoring

### LINKED ISSUE #202: Translate feature is in both unrpyc branches error prone implemented
Noting this down to be complete. _A task for a bad weather day._
Just out of curiosity i try for some time to figure out how this feature works. What i worked out is, you need apparently two runs:

Basis commands as known: `python unrpyc.py /path/to/your/app` and now you may add:
1. With arg `-T file_name`  to write a translation file and if you don't want the default english you pass additional arg `-l language`.
2. Then with arg `-t filename` the file we did write in 1)

Problems in order:
- py3: I forgot with the pathlib move to cast the translation inputs to pathlike but access them like it.(error) Also confused a filename between both. Dang. ~I make a pull for this.~ (edit:Done!)
- ~(After repairing pathlike in py3)~ With run 1) we get the translation file with a short string, but its binary/unknown encoding gibberish.
- Feeding this file to run 2) does nothing I'm aware of.

I tested with multiple games and always the same. Examples:
From a v8.1.3 app: [py3_tl.txt](https://github.com/CensoredUsername/unrpyc/files/14549948/py3_tl.txt)
From a v7.5.3 app: [py2_tl.txt](https://github.com/CensoredUsername/unrpyc/files/14549950/py2_tl.txt)

Oh and i tested even with unrpyc v1.1.8 and got the same result. Maybe i use this wrong?

### PR DESCRIPTION
**Pull request by madeddy**
This closes #202 and partly #211.

So, look what you think.
TL is now as much separated or compartmentalized as possible i think. It could be be cut out without touching much of the other code. I pulled some of the old code into dedicated functions to prevent repeat and as bonus deobfuscation is possible with TL.

Please check also the readme addition if you want to add something(dump opts...) or reword. My EN isn't the best.

### CODE REVIEW

**Comment by CensoredUsername** [comment]
I've pulled it into a `dev_tl` branch in here for now, and added a commit on top of it with some refactoring. Also removed a few branches that weren't necessary any more. Does this test alright for you?

**Comment by madeddy** [comment]
No.

```shell
Extracting translations from /home/olli/.xlib/RPG/_test/TheInn-1.01.01-pc/game/1_01_01/take_me_home_country_roads_images.rpyc...

Traceback (most recent call last):
File "/home/olli/Code/Git/unrpyc/unrpyc.py", line 550, in <module>
main()
File "/home/olli/Code/Git/unrpyc/unrpyc.py", line 487, in main
results = run_workers(worker_tl, args, worklist, args.processes)
File "/home/olli/Code/Git/unrpyc/unrpyc.py", line 265, in run_workers
for result in pool.imap(worker, worker_args, 1):
File "/usr/lib/python3.10/multiprocessing/pool.py", line 873, in next
raise value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<__main__.Context object at 0x76e8f63bc3d0>'. Reason: 'PicklingError("Can't pickle <class 'renpy.ast.Say'>: it's not the same object as renpy.ast.Say")'
```

AFAIK this happens because you removed the pickling of the extracted dialogues in Step1 (i comment there also). This TL setup has quit a few traps build in i'd say.

**Comment by CensoredUsername** [comment]
Fixed.

**Comment by CensoredUsername** [comment]
Actually don't mind that I didn't fix it for sending it to the workers again. Damnit multiprocessing.

**Comment by CensoredUsername** [comment]
But wait, that actually wasn't an issue before. Passing it back to the workers always happened unpickled.

I'm somewhat confused how this was working to begin with. I'll take a better look later.

**Comment by madeddy** [comment]
> What other traps do you mean though?

I played with TL all through Feb-Mar to get it less cumbersome(imo).
- The first mistake was to try to do both steps in one while inside MP. Send file into worker, pull TL for it and send it directly into decompiler. I came then to the conclusion we need another file to do it, but the current process has just the one.
- The other thing i tried was to work on already decompiled files. However the way how the code for TL build is does not allow it i think. 

> Passing it back to the workers always happened unpickled.

Yes. Its the "dialogue" passing out of MP which needs to be masked somehow so the pickler doesn't throw a tantrum. Maybe its just the way these data are stored inside "dialogue" and not the content. No idea really.

**Comment by CensoredUsername** [comment]
Aight, did a final pass over it and tested it, I was able to decompile the tutorial game in a variety of languages now. Looking through the README changes now.

**Comment by CensoredUsername** [comment]
Also pushed README changes.

**Pull request merged**
