### PR TITLE
Suggested changes from #146 / Support renpy 7.5.0

### PR DESCRIPTION
**Pull request by sigio**

### CODE REVIEW

**Comment by sigio** [comment]
With these fixes I could unrpyc all files from AMomentOfBliss 2.1 and 2.2

**Comment by NWPlayer123** [comment]
The main thing is making sure that pre-7.5.0 still works with these fixes, I haven't had a chance to test yet.

**Comment by sigio** [comment]
I'll try some older games that I did without these patches and report back later

**Comment by sigio** [comment]
Testing on a set of 3288 rpyc files from various games:
develop branch decompiles: 3214
renpy750 branch decompiles: 74 that develop branch didn't, but
starting from scratch the renpy750 branch only decompiles: 1856

So it's not backwards compatible as is...

**Comment by sigio** [comment]
On a bigger corpus (26972) of files:
25991 files from various games decompile fine:

current 'master/develop' branch has issues with 47 rpyc files from various renpy 7 games
All of these then do decompile with this renpy750 branch

and 110 files from various renpy 8 games ( 580 out of 690 files decompiled)
and all of these also decompile with this branch...

But starting with this branch shows lots of files not decompiling, so it works for everything I have that fails on 'master', but is not backwards compatible.

**Comment by Bexa2** [comment]
For some reason the game 'High School Days' fails with `renpy.python` and works with `renpy.revertable`
but  'SexNote-0.19.5a-pc' fails with `renpy.revertable` and works with `renpy.python`
Is there any way to use both?

Error is the same ```
File "C:\Users\Bexa\AppData\Local\Programs\Python\Python310\lib\pickle.py", line 1829, in load_setitems
    dict[items[i]] = items[i + 1]
TypeError: 'RevertableDict' object does not support item assignment```

**Comment by MARLBORO-NEW** [comment]
This might help: https://github.com/CensoredUsername/unrpyc/issues/156#issue-1416743346

**Comment by CensoredUsername** [comment]
I've made these changes in a backwards compatible manner in f5f973f and 964032f.

**Pull request closed without merging**
